version: "3.9"

services:
  web:
    build: .
    command: gunicorn hikingbees.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - hikingbees_media_data:/app/media   # Persist media uploads
      - hikingbees_static_data:/app/static # Persist static files
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  hikingbees_media_data:
  hikingbees_static_data:
